/*
 * This file is generated by jOOQ.
 */
package mochegov.game.db.jooq.domain;


import mochegov.game.db.jooq.domain.tables.Game;
import mochegov.game.db.jooq.domain.tables.Move;
import mochegov.game.db.jooq.domain.tables.Player;
import mochegov.game.db.jooq.domain.tables.records.GameRecord;
import mochegov.game.db.jooq.domain.tables.records.MoveRecord;
import mochegov.game.db.jooq.domain.tables.records.PlayerRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GameRecord> CONSTRAINT_2 = Internal.createUniqueKey(Game.GAME, DSL.name("CONSTRAINT_2"), new TableField[] { Game.GAME.ID }, true);
    public static final UniqueKey<MoveRecord> CONSTRAINT_24 = Internal.createUniqueKey(Move.MOVE, DSL.name("CONSTRAINT_24"), new TableField[] { Move.MOVE.ID }, true);
    public static final UniqueKey<PlayerRecord> CONSTRAINT_8 = Internal.createUniqueKey(Player.PLAYER, DSL.name("CONSTRAINT_8"), new TableField[] { Player.PLAYER.PLAYER_NAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<GameRecord, PlayerRecord> CONSTRAINT_21 = Internal.createForeignKey(Game.GAME, DSL.name("CONSTRAINT_21"), new TableField[] { Game.GAME.PLAYER_NAME }, Keys.CONSTRAINT_8, new TableField[] { Player.PLAYER.PLAYER_NAME }, true);
    public static final ForeignKey<MoveRecord, GameRecord> CONSTRAINT_243 = Internal.createForeignKey(Move.MOVE, DSL.name("CONSTRAINT_243"), new TableField[] { Move.MOVE.GAME_ID }, Keys.CONSTRAINT_2, new TableField[] { Game.GAME.ID }, true);
}
