/*
 * This file is generated by jOOQ.
 */
package mochegov.game.db.jooq.domain;


import java.util.Arrays;
import java.util.List;

import mochegov.game.db.jooq.domain.tables.Game;
import mochegov.game.db.jooq.domain.tables.Move;
import mochegov.game.db.jooq.domain.tables.Player;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * Games
     */
    public final Game GAME = Game.GAME;

    /**
     * Game moves
     */
    public final Move MOVE = Move.MOVE;

    /**
     * Players
     */
    public final Player PLAYER = Player.PLAYER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Game.GAME,
            Move.MOVE,
            Player.PLAYER
        );
    }
}
