/*
 * This file is generated by jOOQ.
 */
package mochegov.game.db.jooq.domain;


import mochegov.game.db.jooq.domain.tables.Game;
import mochegov.game.db.jooq.domain.tables.Move;
import mochegov.game.db.jooq.domain.tables.Player;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Games
     */
    public static final Game GAME = Game.GAME;

    /**
     * Game moves
     */
    public static final Move MOVE = Move.MOVE;

    /**
     * Players
     */
    public static final Player PLAYER = Player.PLAYER;
}
