/*
 * This file is generated by jOOQ.
 */
package mochegov.game.db.jooq.domain.tables.records;


import java.time.LocalDateTime;

import mochegov.game.db.jooq.domain.tables.Game;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Games
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameRecord extends UpdatableRecordImpl<GameRecord> implements Record5<Integer, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.GAME.ID</code>. Unique identifier
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.GAME.ID</code>. Unique identifier
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.GAME.PLAYER_NAME</code>. Name of player
     */
    public void setPlayerName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.GAME.PLAYER_NAME</code>. Name of player
     */
    public String getPlayerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.GAME.GAME_STATE</code>. State of game
     */
    public void setGameState(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.GAME.GAME_STATE</code>. State of game
     */
    public String getGameState() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.GAME.CREATED_AT</code>. Creation timestamp
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.GAME.CREATED_AT</code>. Creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>PUBLIC.GAME.UPDATED_AT</code>. Update timestamp
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.GAME.UPDATED_AT</code>. Update timestamp
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Game.GAME.ID;
    }

    @Override
    public Field<String> field2() {
        return Game.GAME.PLAYER_NAME;
    }

    @Override
    public Field<String> field3() {
        return Game.GAME.GAME_STATE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Game.GAME.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Game.GAME.UPDATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPlayerName();
    }

    @Override
    public String component3() {
        return getGameState();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPlayerName();
    }

    @Override
    public String value3() {
        return getGameState();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    public GameRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GameRecord value2(String value) {
        setPlayerName(value);
        return this;
    }

    @Override
    public GameRecord value3(String value) {
        setGameState(value);
        return this;
    }

    @Override
    public GameRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public GameRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public GameRecord values(Integer value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameRecord
     */
    public GameRecord() {
        super(Game.GAME);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(Integer id, String playerName, String gameState, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Game.GAME);

        setId(id);
        setPlayerName(playerName);
        setGameState(gameState);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
